#
# This workflow will build and run all unit tests.
#

name: AzureExt-CI
on:
  pull_request:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, arm64]
        os: [windows-latest, windows-11-arm]
        dotnet-version: ['8.0.x']
        exclude:
        - os: windows-latest
          platform: arm64
        - os: windows-11-arm
          platform: x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        clean: true

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
      with:
        vs-version: '17.5'

    - name: Download nuget
      run: |
        mkdir ".\.nuget"
        Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile ".\.nuget\nuget.exe"

    - name: Find VsDevCmd.bat
      run: |
        $VSDevCmd = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere" -latest -find Common7\tools\VSDevCmd.bat
        if (!$VSDevCmd) { exit 1 }
        echo "Using VSDevCmd: ${VSDevCmd}"
        Add-Content $env:GITHUB_ENV "VSDevCmd=$VSDevCmd"

    - name: Restore dependencies
      run: dotnet restore AzureExtension.sln -p:PublishReadyToRun=true

    - name: Build_CmdPalAzureExtension
      run: cmd /c "$env:VSDevCmd" "&" msbuild /p:Configuration=${{ matrix.configuration }},Platform=${{ matrix.platform }} /restore AzureExtension.sln

    - name: Find vstest.console.exe
      if: ${{ matrix.platform != 'arm64' }}
      run: |
        $VSDevTestCmd = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere" -latest -prerelease -products * -find **\TestPlatform\vstest.console.exe
        if (!$VSDevTestCmd) { exit 1 }
        echo "Using VSDevTestCmd: ${VSDevTestCmd}"
        Add-Content $env:GITHUB_ENV "VSDevTestCmd=$VSDevTestCmd"

    - name: UnitTests
      if: ${{ matrix.platform != 'arm64' }}
      run: cmd /c "$env:VSDevTestCmd" /Platform:${{ matrix.platform }} /TestCaseFilter:"TestCategory!=LiveData" BuildOutput\\${{ matrix.configuration }}\\${{ matrix.platform }}\\AzureExtension.Test\\AzureExtension.Test.dll